experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"
    theme-park:
      moduleName: "github.com/packruler/traefik-themepark"
      version: "v1.2.0"
api:
  dashboard: true
  insecure: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: jdemmers.xyz
            sans:
              - "*.jdemmers.xyz"
          - main: jdemmers.dev
            sans: 
              - "*.jdemmers.dev"
  traefik:
    address: ":8080"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/config"
certificatesResolvers:
  cloudflare:
    acme:
      email: admin@jdemmers.xyz
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"