version: "3.2"
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8085:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.qbittorrent/config:/config
      - /data/torrents:/data/torrents:rw